- src/main/java/spireMapOverhaul/BetterMapGenerator.java
- src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java
- src/main/java/spireMapOverhaul/abstracts/AbstractSMOCard.java
- src/main/java/spireMapOverhaul/abstracts/AbstractSMOMonster.java
- src/main/java/spireMapOverhaul/abstracts/AbstractSMOPower.java
- src/main/java/spireMapOverhaul/abstracts/AbstractSMORelic.java
- src/main/java/spireMapOverhaul/abstracts/AbstractZone.java
- src/main/java/spireMapOverhaul/abstracts/LambdaPower.java
- src/main/java/spireMapOverhaul/patches/BetterMapGenPatch.java
- src/main/java/spireMapOverhaul/patches/BetterMapRenderPatch.java
- src/main/java/spireMapOverhaul/patches/ZonePatches.java
- src/main/java/spireMapOverhaul/util/CardArtRoller.java
- src/main/java/spireMapOverhaul/zones/AbstractZone.java
- src/main/java/spireMapOverhaul/zones/example/CoolExampleEvent.java
- src/main/java/spireMapOverhaul/zones/example/PlaceholderZone.java
- src/main/resources/anniv6Resources/localization/eng/Placeholder/UIstrings.json
file reorganization - 
If all stuff for zones is going in the zone's package, I've moved the abstracts all to one package since those packages for individual types of content shouldn't be used.
set up loading localization files for zones/autoadd for them.
zones themselves -
map gen, some placeholder graphical stuff
> some initial stuff

- src/main/java/spireMapOverhaul/BetterMapGenerator.java
- src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java
- src/main/java/spireMapOverhaul/abstracts/AbstractZone.java
- src/main/java/spireMapOverhaul/util/ZoneShapeMaker.java
- src/main/java/spireMapOverhaul/zones/example/PlaceholderZone.java
- src/main/resources/anniv6Resources/shaders/shapeMaker/fragment.fs
main thing was to try to remove some branching/other adjustments to zone shape generator thing (optimization)
then, I had to adjust parameters used as a result
looks a bit different, feel free to adjust parameters more later if not happy with them
> shader stuff

- src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java
- src/main/java/spireMapOverhaul/util/ZoneShapeMaker.java
> Fix crash due to not loading zone strings from unfilteredAllZones

- src/main/java/spireMapOverhaul/BetterMapGenerator.java
- src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java
- src/main/java/spireMapOverhaul/abstracts/AbstractZone.java
- src/main/java/spireMapOverhaul/zones/example/ExampleEncounterModifyingZone.java
I hope that just reading the code gives a fairly clear idea of what's going on, so not going to add many comments to this PR.
>  Add functions that can be overridden to prevent a zone from spawning in specific rows

- src/main/java/spireMapOverhaul/util/ZoneShapeMaker.java
I'll never be done with these :p
> Shape tweaks

- src/main/resources/anniv6Resources/shaders/shapeMaker/fragment.fs
should not change anything visually
step is just 0 or 1 depending on comparison between two values
> swap to using step function

- example-pom.txt
If we are not good with using 1.7.22 then we can always lower the version. From my testing this should work fine.
> Add support for kotlin

- example-pom.txt
Add kotlin-reflect and enable incremental compiling
> More kotlin

- src/main/java/spireMapOverhaul/abstracts/AbstractZone.java
- src/main/java/spireMapOverhaul/util/ZoneShapeMaker.java
- src/main/java/spireMapOverhaul/zones/example/ExampleRewardModifyingZone.java
- src/main/java/spireMapOverhaul/zones/invasion/InvasionZone.java
- src/main/resources/anniv6Resources/shaders/shapeMaker/fragment.fs
- src/main/resources/anniv6Resources/shaders/shapeMaker/vertex.vs
This makes icon a little faint but I think I'll have to write a shader to resolve that issue :)
So that's for later
> Making zone shapes more transparent

- src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java
If I keep up like this I'll have the highest number of PR merges
> Config menu using tootip

- src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java
if keyword has ID, store in map
> map keywords with an ID defined

- src/main/java/spireMapOverhaul/patches/ZonePatches.java
- src/main/java/spireMapOverhaul/zoneInterfaces/RenderableZone.java
- src/main/java/spireMapOverhaul/zones/example/PlaceholderZone.java
Adds rendering for zones and provides and update hook
> Zone Rendering and Update hooks

- src/main/java/spireMapOverhaul/patches/ZonePatches.java
- src/main/java/spireMapOverhaul/zoneInterfaces/RenderableZone.java
- src/main/java/spireMapOverhaul/zones/brokenSpace/BrokenSpaceZone.java
- src/main/java/spireMapOverhaul/zones/brokenSpace/patches/BrokenSpaceRenderPatch.java
- src/main/java/spireMapOverhaul/zones/brokenSpace/relics/BrokenRelic.java
- src/main/resources/anniv6Resources/shaders/BrokenSpace/Glitch.fs
Added postRenderBackground to renderable zone, used to make changes to the background of the scene.
Update Broken Space shaders and apply a slow effect to the background of affected rooms.
> Add PostBackgroundRender hook to RenderableZone interface, update BrokenSpace to make use of it

- src/main/java/spireMapOverhaul/zones/brokenSpace/relics/BrokenMatryoshka.java
Should fix a commodification crash when you pick up Broken Matryoshka
> Fix Broken Matryoshka crash

- src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java
- src/main/java/spireMapOverhaul/zones/brokenspace/BrokenSpaceZone.java
- src/main/java/spireMapOverhaul/zones/brokenspace/actions/BetterTextCenteredAction.java
- src/main/java/spireMapOverhaul/zones/brokenspace/cardmods/UnreadableCardMod.java
- src/main/java/spireMapOverhaul/zones/brokenspace/events/FakeEventRoom.java
- src/main/java/spireMapOverhaul/zones/brokenspace/events/WingBootEvent.java
- src/main/java/spireMapOverhaul/zones/brokenspace/patches/BrokenSpaceRenderPatch.java
- src/main/java/spireMapOverhaul/zones/brokenspace/patches/UnreadableCardArtPatch.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenDamaru.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenDataDisk.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenMatryoshka.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenMawBank.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenOmamori.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenPrayerWheel.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenRedSkull.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenRelic.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenSingingBowl.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenSneckoEye.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenSneckoSkull.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenSozu.java
- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenWingBoots.java
- src/main/resources/anniv6Resources/localization/eng/BrokenSpace/UIstrings.json
simple changes stuck in the scrapped void seed branch.
> Change caps to be consistant, make broken space description a little more interesting

- src/main/java/spireMapOverhaul/zones/storm/StormZone.java
Adding a shader to the storm zone map
> feat: Adding a shader to the storm zone map

- src/main/java/spireMapOverhaul/zones/characterinfluence/CharacterInfluenceEvent.java
Should fix the event, it needs it to not be able to be exploited by save & quits etc
> Fixes CharacterInfluenceEvent: Adds endsWithRewardsUI to event

- src/main/java/spireMapOverhaul/zones/beastslair/BeastsLairEvent.java
- src/main/java/spireMapOverhaul/zones/beastslair/powers/DamageUpPower.java
- src/main/java/spireMapOverhaul/zones/beastslair/powers/FuryPower.java
- src/main/resources/anniv6Resources/localization/eng/BeastsLair/Powerstrings.json
Bosses now gain 10% damage up at the end of their turn, instead of when the player plays a card. this should lessen the problem of the original effect punishing high card builds a little too much.
> Rework BeastsLair fury mechanic.

- src/main/java/spireMapOverhaul/zones/thefog/relics/StoneFragment.java
- src/main/resources/anniv6Resources/localization/eng/TheFog/Relicstrings.json
The special event Relic from The Fog zone
> Change (nerf) Stone Fragment

- src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java
- src/main/java/spireMapOverhaul/zones/storm/StormZone.java
- src/main/java/spireMapOverhaul/zones/storm/patches/DampCardPatch.java
- src/main/java/spireMapOverhaul/zones/storm/patches/ElectricCardPatch.java
- src/main/java/spireMapOverhaul/zones/storm/patches/RainPatch.java
- src/main/java/spireMapOverhaul/zones/thefog/patches/FogShaderPatch.java
- src/main/resources/anniv6Resources/localization/eng/UIstrings.json
I passed on making this config work on Broken Space Zone because I haven't heard any complaints about it. I did try for a bit, but stopped when I ran into some issues getting it to work that I didn't feel like dealing with. Can revisit later if need be.
> feat: Adding toggle for enabling/disabling shaders for Storm and The Fog Zone

- src/main/java/spireMapOverhaul/zones/manasurge/ManaSurgeZone.java
- src/main/java/spireMapOverhaul/zones/manasurge/events/ManaCycloneEvent.java
- src/main/resources/anniv6Resources/localization/eng/ManaSurge/Eventstrings.json
Changed some event strings, did condition checks to ensure it'll only spawn when options are actually able to be selected.
Adjusted Phases so that effects occur more naturally.
Changed forced Event to zoneSpecificEventRate.
Adjusted ShowCardBrieflyEffects so that the centering is actually correct.
> Events updated.

- src/main/java/spireMapOverhaul/zones/manasurge/events/ManaCycloneEvent.java
- src/main/java/spireMapOverhaul/zones/manasurge/ui/campfire/CampfireEnchantEffect.java
- src/main/java/spireMapOverhaul/zones/manasurge/vfx/EnchantBlightEffect.java
- src/main/java/spireMapOverhaul/zones/manasurge/vfx/ManaExhaustEmberEffect.java
- src/main/java/spireMapOverhaul/zones/manasurge/vfx/ManaFlameParticleEffect.java
Just took base code of Inflame effects, adjusted colours and added to all instances of permanently Enchanting/Blighting cards.
> Mana Surge Enchant/Blight VFX

- src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java
> Fix monster strings not being loaded

- src/main/java/spireMapOverhaul/zones/manasurge/ManaSurgeZone.java
just a slight adjustment to the mana surge zone color - i feel like more purple than blue fits a bit more and it helps differentiate it a bit from the mirror zone.
> Mana Surge Zone Color Adjustment

- src/main/java/spireMapOverhaul/abstracts/AbstractZone.java
- src/main/java/spireMapOverhaul/patches/RenderZoneNamePatch.java
> Render zone names on top of paths on the map

- src/main/java/spireMapOverhaul/zones/beastslair/BeastsLairEvent.java
> reduce Beasts lair hp increase

- src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenMatryoshka.java
- src/main/java/spireMapOverhaul/zones/goldencurse/GoldenCurseZone.java
It affected golden curse, and Broken Matryoshka.
> Fix bug with rewards in Golden Curse and Broken Space

- src/main/java/spireMapOverhaul/abstracts/AbstractZone.java
- src/main/java/spireMapOverhaul/patches/ZonePatches.java
Leaving this one for you to take a look at and merge. The primary reason is so that you're aware of how this is being handled, the secondary reason is because I think it's sort of cool and you might be curious.
> When the Dark Map mod is active, adjust dark-colored zones to make them easier to see

- src/main/java/spireMapOverhaul/zones/grass/GrassZone.java
- src/main/java/spireMapOverhaul/zones/grass/vegetables/AbstractVegetable.java
- Fix grass hitbox
- Fix grass position
- Fix grass spawning outside monster rooms
> More Grass Zone fixes

- src/main/java/spireMapOverhaul/zones/candyland/CandyLand.java
- src/main/java/spireMapOverhaul/zones/invasion/powers/HydraHeadsPower.java
- src/main/kotlin/spireMapOverhaul/zones/humility/HumilityZone.kt
- src/main/resources/anniv6Resources/bestiary/eng/Invasion/bestiary.json
- src/main/resources/anniv6Resources/localization/eng/Invasion/Monsterstrings.json
* Humility zone: restrict Humility zone to spawning in the base game acts only
* Invasion zone: fix power for Hydra heads not saying what the damage threshold is
* Candy Land zone: fix handling for card rewards with special rarity cards in them
* Invasion zone: add missing text entries for Hatchling encounter
> Fix a variety of bugs

- src/main/java/spireMapOverhaul/zones/characterinfluence/CharacterInfluenceZone.java
i wrote this in github and haven't made sure it packages
> avoid transparent color

- src/main/resources/anniv6Resources/localization/eng/ManaSurge/Powerstrings.json
> Mana Surge - updated powerstrings to match modifier chance

- src/main/java/spireMapOverhaul/zones/beastslair/BeastsLairZone.java
- src/main/java/spireMapOverhaul/zones/divinitiesgaze/DivinitiesGazeZone.java
Not really a bugfix, just minor stuff I found during my check of RNG use while investigating save/load instability.
> Two minor tweaks to RNG uses to be more in line with best practice

- src/main/java/spireMapOverhaul/zones/divinitiesgaze/cards/Inevitability.java
FIX: Inevitability now properly scales block
> Divinities Gaze: Fix Inevitability Scaling

- src/main/java/spireMapOverhaul/zones/gravewoodGrove/GravewoodGroveZone.java
- src/main/java/spireMapOverhaul/zones/gravewoodGrove/GravewoodShaderPatch.java
- src/main/resources/anniv6Resources/shaders/gravewoodGrove/fragment.fs
- src/main/resources/anniv6Resources/shaders/gravewoodGrove/vertex.vs
Biome now is properly desaturated
Edit: Maybe this isn't actually better, the brown tint from before does have some charm to it. Either way, you decide, feel free to reject this
> Improved Gravewood Grove visuals(?)
