erasels/SpireMapOverhaul

src/main/java/spireMapOverhaul/patches/interfacePatches/RewardModifierPatches.java, src/main/java/spireMapOverhaul/zoneInterfaces/IRewardModifyingZone.java, src/main/java/spireMapOverhaul/zones/example/ExampleRewardModifyingZone.java, src/main/resources/anniv6Resources/localization/eng/ExampleRewardModifying/UIstrings.json
This is the first cut of `IRewardModifyingZone`. I put this together pretty quickly so I haven't tested all the small interactions and edge cases yet, but the core should work.
I built this with a few thoughts in mind:
* Provide a simple way of doing common operations
* Start with a core set on methods with high flexibility so that a broad range of use cases are supported with a bit more work
* Make it hard to screw things up in a way that makes saving and reloading change the rewards
The documentation comments plus the example will hopefully be enough to understand what's going on. 
For the overall shape of the API, I took a look through the ideas spreadsheet and this should meet the needs of many of the reward modifiers listed so far. There are some potential extensions to this that I …
=> Add IRewardModifyingZone

src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java, src/main/java/spireMapOverhaul/abstracts/AbstractZone.java, src/main/java/spireMapOverhaul/patches/ZonePerFloorRunHistoryPatch.java, src/main/resources/anniv6Resources/localization/eng/UIstrings.json
I like run history having information like this, so I went ahead and implemented it. The patch is adapted from the patches I've written for stuff like this in other mods. 
Here's how it looks right now:
=> Show the zone for each node in the run history screen

src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java
The loading of Eventstrings for zones was omitted. I've added it here.
=> Add loading for Zone Eventstrings.

src/main/java/spireMapOverhaul/util/ZoneShapeMaker.java, src/main/resources/anniv6Resources/shaders/shapeMaker/fragment.fs, src/main/resources/anniv6Resources/shaders/shapeMaker/vertex.vs
This may need some testing on Windows and Linux, but this should fix an issue where zone outlines do not render when on a Mac. If needed, we may have to add some way to swap between shaders depending on platform. for now I'm hoping this will work out of the box, and I'll be able to test it soon. Also added a log for the shader just in case we run into an issue like this again.
=> Fix zone outline shader not rendering on Mac.

src/main/java/spireMapOverhaul/zones/storm/StormZone.java, src/main/java/spireMapOverhaul/zones/storm/patches/AddLightningPatch.java, src/main/java/spireMapOverhaul/zones/storm/powers/ConduitPower.java, src/main/java/spireMapOverhaul/zones/storm/vfx/AlwaysBehindLightningEffect.java, src/main/java/spireMapOverhaul/zones/storm/vfx/DispelPlayerElectricEffect.java, src/main/resources/anniv6Resources/localization/eng/Storm/Powerstrings.json
- Conduit triggers at the end of the target's turn. Player's block was disappating before the trigger at end of round
- Fix bug where the spark vfx could trigger on non-existent targets, both dead and in a new room
- Added LightOut support for lightning background vfx
- Made the Conduit spark vfx happen less frequently
=> fix: Various Lightning Fixes

src/main/java/spireMapOverhaul/patches/EventGenPatch.java, src/main/java/spireMapOverhaul/zoneInterfaces/ModifiedEventRateZone.java, src/main/java/spireMapOverhaul/zones/example/PlaceholderZone.java, src/main/java/spireMapOverhaul/zones/manasurge/ManaSurgeZone.java
It seems that forced events don't get added to SeenEvents.seenEvents spirefield on AbstractPlayer. It happens due to getEvent never being called if we force an event.
To fix this, I manually add it in the `modifyGen` patch, however getting the correct event ID was hard in that place so I rewrote some code so that we're working with IDs for the most part.
=> Fix forced events not being added to seenEvents

src/main/java/spireMapOverhaul/BetterMapGenerator.java, src/main/java/spireMapOverhaul/SpireAnniversary6Mod.java, src/main/java/spireMapOverhaul/patches/CharacterSelectScreenPatch.java, src/main/java/spireMapOverhaul/patches/InitializeCurrentRunPatch.java, src/main/java/spireMapOverhaul/util/ActUtil.java, src/main/resources/anniv6Resources/localization/eng/UIstrings.json
I took a bit of time to implement this since even if we end up not wanting it in the full release, I think it's a good thing to have in place for playtesting. (I certainly want it for my own playtesting, at the very least.)
We can discuss exactly how we want to merge this -- as is, or with some kind of setting or config option or console command for it, or some other option. I do want to get some version of these changes merged in, though, since it has a better system for recording which zones are valid for your current run (using a savable instead of a config).
=> Prevent zones from showing up more than once in a run

src/main/java/spireMapOverhaul/zones/grass/GrassZone.java, src/main/java/spireMapOverhaul/zones/grass/actions/ThrowVegetableEffect.java, src/main/java/spireMapOverhaul/zones/grass/vegetables/AbstractVegetableData.java
- Adjustments for vegetable throwing VFX
- Fix wrong name being used in relic rewards when the Grass zone replaces them
=> Grass zone fixes

src/main/java/spireMapOverhaul/zones/ambushed/AmbushedZone.java, src/main/resources/anniv6Resources/localization/eng/Ambushed/UIstrings.json
The potential for 4 straight floors of card draw cards could feel bad for players in Act 1 because only the utility of the deck improves when they need block/damage, so reducing height by 25% should help with that frustration.
Also I simply don't have enough combats for the zone, 4 nodes made it very likely for repeats to occur
=> (Ambushed) Reduced zone size, updated UI strings, added Courier support

src/main/resources/anniv6Resources/localization/eng/DivinitiesGaze/UIstrings.json
Shorter name to reduce odds of overlap, remove the word "zone" from description.
=> Update Divinities' Gaze Zone description and name

src/main/java/spireMapOverhaul/zones/mirror/cards/MirrorMove.java
Turns out the crash happens if `moveData` is null. The first commit fixes this.
But why `moveData` was null in the first place? Because Mirror Move had some "transformation" mechanic to it. I wanted all instances of Mirror Move to have the same move data, so it changed it in `applyPowers`. Though it never changes while in Exhaust pile, creating inconsistencies like:
- After you Exhume a Mirror Move, it changes its description.
- When Mirror Move is exhausted due to Ethereal, it **sometimes** changes its data to null. (This is probably what happened in the crash report)
I'm removing this confusing behavior in the second commit. Now, once the `moveData` of Mirror Move is set, it never changes.
=> Fix Mirror Move crash

src/main/java/spireMapOverhaul/util/EventTooltipCreator.java, src/main/java/spireMapOverhaul/zones/divinitiesgaze/divinities/DivineBeing.java, src/main/java/spireMapOverhaul/zones/divinitiesgaze/divinities/impl/Eclectic.java, src/main/java/spireMapOverhaul/zones/divinitiesgaze/divinities/impl/Jurors.java, src/main/java/spireMapOverhaul/zones/divinitiesgaze/events/DivineVisitor.java, src/main/java/spireMapOverhaul/zones/divinitiesgaze/powers/VerdictPower.java, src/main/java/spireMapOverhaul/zones/manasurge/events/ManaCycloneEvent.java, src/main/resources/anniv6Resources/localization/eng/DivinitiesGaze/Keywordstrings.json, src/main/resources/anniv6Resources/localization/eng/DivinitiesGaze/UIstrings.json
ADD: Utility for creating Circlets to display tooltips on PhasedEvent options
ADD: Tooltip for Verdict power to Jurors' options in Divine Visitor event
CHANGE: Mana Storm event now uses Circlet utility
BALANCE: Eclectic event cards to choose from: 20 -> 10
=> Update Jurors with Verdict tooltip in event and add utility for creating these tooltips. Rebalance Eclectic.

src/main/resources/anniv6Resources/shaders/fog/fragment.fs
The fractal browning motion represents a massive computational load, both of my changes try to reduce the amount of times the noise function within is called while not affecting visuals overly much.
Changes are:
- Reduce amount of iterations within fractal by 2 (this will cause the fog to be more uniform but it is not really noticeable)
- Break out of fog generation loop if the fog is too small (this being too big will cause visual artifactin close to the mouse once moved but I think I found a decent breakpoint)
Leaving thsi PR up so people with bad PCs can test it.
=> Optimize Fog Shader Performance

src/main/java/spireMapOverhaul/zones/heavenlyClouds/FlightMod.java, src/main/resources/anniv6Resources/localization/eng/HeavenlyClouds/Keywordstrings.json, src/main/resources/anniv6Resources/localization/eng/HeavenlyClouds/UIstrings.json
This is the same way Electric (from the Storm zone) does it, and I think the UX is better. You don't get cards with super tiny text, and it's clear when the mod has been triggered already this combat.
=> Heavenly Clouds zone: change Flighty to remove itself after being triggered and to use a tooltip instead of adding to the card description

src/main/java/spireMapOverhaul/zones/grass/GrassZone.java
This fixes both the issue that was reported in the Workshop thread and other issues related to the relics still being in the relic pool.
=> Grass zone: fix spawning duplicate relics

src/main/java/spireMapOverhaul/BetterMapGenerator.java
noticed too many paths that quickly reconnect, probably caused by this not properly applying
can and will break in-progress runs though, due to changing map gen
=> fix map gen thingy

src/main/java/spireMapOverhaul/zones/brokenspace/relics/BrokenMawBank.java
This can happen if you save and reload on the floor after the shop where it triggers. Plus there were some other save and load issues. Also changed it to use the standard system for used up relics.
=> Broken Space zone: fix being able to get the benefit from Broken Maw Bank multiple times

src/main/java/spireMapOverhaul/zones/divinitiesgaze/cards/Inevitability.java, src/main/java/spireMapOverhaul/zones/divinitiesgaze/powers/VerdictPower.java, src/main/resources/anniv6Resources/localization/eng/DivinitiesGaze/Cardstrings.json, src/main/resources/anniv6Resources/localization/zhs/DivinitiesGaze/Cardstrings.json
CHANGE: Moved Inevitability block to magic number to not give the implication that it scales.
BALANCE: Increased base block on Inevitability+ by 1.
VISUAL: Verdict's Health Bar Render now shows stacks less 1 instead of stacks. This means that a fully-shaded bar now always indicates that the enemy will die at the start of its next turn.
=> Divinities' Gaze: Verdict and Inevitability Adjustments

src/main/java/spireMapOverhaul/zones/monsterZoo/MonsterZooZone.java, src/main/java/spireMapOverhaul/zones/wildfire/Wildfire.java
This something Alch brought up. See https://discord.com/channels/309399445785673728/398373038732738570/1217272840227917894 for the suggestion he made (there's some context before that and some discussion after it as well). The short version is that this will have less impact on the overall distribution of room types than the previous code.
It seemed like a reasonable change to make, so I implemented it and did a bit of testing to make sure that this works properly (specifically making sure that elite rooms sometimes show up in either zones, and that campfires sometimes show up for Wildfire).
Leaving this for you to look over and merge.
=> Monster Zoo/Wildfire zones: change how the rooms are placed to avoid reducing the total number of non-monster rooms on the map

src/main/resources/anniv6Resources/bestiary/eng/Junkyard/bestiary.json
As I have time, I plan to add Bestiary entries for zones that don't have them. Picked Junkyard to start with as one that would benefit from it since the enemies have some unusual moves.
=> Bestiary: add Junkyard entries

src/main/java/spireMapOverhaul/zones/smithsFolly/SmithsFolly.java
Two free upgrades is highly valuable, and the events that Smith's Folly can generate are also very powerful. It also opens up another pathing option for those going for the Emerald Key. Previously, it was too easy to reap the rewards of the biome without punishment. This change should increase likelihood of combat encounters in the biome, making the decision to path here a bit less obvious.
=> Smith's Folly: Biome no longer guarantees an event

src/main/java/spireMapOverhaul/zones/volatileGrounds/monsters/Eruptor.java, src/main/java/spireMapOverhaul/zones/volatileGrounds/monsters/GremlinArchmage.java, src/main/java/spireMapOverhaul/zones/volatileGrounds/monsters/HeatBlister.java, src/main/java/spireMapOverhaul/zones/volatileGrounds/monsters/SunStoneShard.java, src/main/java/spireMapOverhaul/zones/volatileGrounds/monsters/UnstableSunstone.java, src/main/resources/anniv6Resources/bestiary/eng/VolatileGrounds/bestiary.json
I noticed a few issues with the enemies while making Bestiary entries for Volatile Grounds, so I fixed them along the way.
Here are the key changes:
* Bestiary: add Volatile Grounds entries
* Volatile Grounds zone: show names for most enemy moves
* Volatile Grounds zone: fix Heat Blister's attack and debuff doing the wrong amount of damage
* Volatile Grounds zone: fix Heat Blister having the wrong explode amount on A17+
* Volatile Grounds zone: fix Gremlin Archmage having a mismatch between the damage it dealt and the damage shown in its intent
=> Volatile Grounds Bestiary entries and bug fixes

src/main/java/spireMapOverhaul/zones/gremlincamp/GremlinCamp.java, src/main/java/spireMapOverhaul/zones/monsterZoo/MonsterZooZone.java, src/main/java/spireMapOverhaul/zones/smithsFolly/SmithsFolly.java, src/main/java/spireMapOverhaul/zones/thefog/TheFogZone.java
The intent of this is to avoid crashes such as 
https://discord.com/channels/309399445785673728/724725673578463232/1229505634186301490. It's unclear what the root cause of this crash is (my best guess is some mod that messes with combats), so rather than try work out which of the billion mods it might be, I'm fixing the immediate symptom that causes the crash. The best case is that this fully fixes things. If not, it may let people get further along in the room loading process and get more information that could lead to the root cause.
=> Add safeguards to prevent zones that buff or debuff monsters from crashing if there's a fight that starts without monsters

src/main/java/spireMapOverhaul/zones/ambushed/patches/MonsterDeathPatch.java, src/main/java/spireMapOverhaul/zones/ambushed/patches/MonsterEscapePatch.java
This mostly affected Smoke Bomb's "use" functionality, but also addresses general polish as well as making it so the player, if facing a Looter who is escaping, automatically turns around afterwards
=> Ambushed - Fixed bugged behavior when a monster escapes combat in a way other than death

src/main/java/spireMapOverhaul/abstracts/AbstractZone.java
Previously, for me at least, a new issue emerged where some biomes would have their transparencies heavily increased. See below, there are three zones: Gremlin Camp, where the zone outline is entirely invisible, Heavenly Clouds, where the zone outline is BARELY visible, and Mana Surge, where it looks fine.
This change makes it so that all biomes have consistent transparency:
Again, this was a personal issue and I'm not sure how many others have experienced the same transparency discrepancies, but I hope there's some others out there who are helped by this.
=> Changed rendering logic for zones on the map

src/main/java/spireMapOverhaul/zones/humidity/encounters/monsters/HumidityCenturion.java
Pull 278 commit fcd8120 removed a large number of patches to vanilla Centurion and replaced them with a dedicated HumidityCenturion monster for the "Owner" vs "Murderer" encounter.  The behavior of HumidityCenturion is meant to be identical to the previously-patched Centurion, including permanent "enrage mode" by setting the aliveCount variable to 1.
When writing HumidityCenturion, I overlooked that the getMove function calculates aliveCount in two different places and forgot to set it in the second situation. This caused "Owner" to occasionally drop out of enrage mode and shield the player instead of attacking "Murderer".
=> Bugfix: Humidity Centurion "Owner" occasionally shielded player instead of attacking like he's supposed to

src/main/java/spireMapOverhaul/zones/humidity/HumidityZone.java, src/main/java/spireMapOverhaul/zones/humidity/cards/powerelic/implementation/PowerelicCard.java, src/main/java/spireMapOverhaul/zones/humidity/cards/powerelic/implementation/RemoveRelicGameEffect.java, src/main/java/spireMapOverhaul/zones/humidity/powers/BaseballPower.java
_"game crashed in heavenly clouds when stunning against a single slaver"_
_"Cause:
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at java.lang.String.charAt(String.java:658)
at spireMapOverhaul.zones.humidity.powers.BaseballPower$ReplaceOverheadTextPatch.Foo(BaseballPower.java:67)"_
Diagnosis: InvisibleFlightTracker's displayed name is "".
Added "if(msg[0]==null)return;" and "if(msg[0].isEmpty())return;" to start of patch.
--
_"I confirmed by reloading the save that the Feather Duster didn't crash when removing anything else, it was just the one that was 'active'. I also removed the Juzu Bracelet Powerelic through the console, and had **no problems** when doing so, indicating it likely has to do with animation or something?"_
Diagnosis: Relics which remove cards …
=> Crash fixes
